### ISSUE TITLE
Typo on Site Footer 

### ISSUE THREAD

**Issue by ryanwiemer** [philhawksworth/hawksworx.com#2]
Hey Phil, 

I was just looking around your site and noticed a minor typo on your site footer. You misspelled "Netlify" as "Netify". Just an FYI.

https://github.com/philhawksworth/hawksworx.com/blob/master/src/_layouts/base.html#L95

Cheers, 
Ryan

**Comment by philhawksworth** [comment]
Thanks Ryan. Sharp eyes!
Fixed.
